idf_component_register(SRCS
    "main.c"
    "utilite/app_handlers.c"
    "dmx/dmx.c"
    "dmx/dmx_led.c"
    "utilite/effects.c"
    "utilite/settings_manager.c"
    "utilite/patch_manager.c"
    "utilite/udp_test.c"
    "led_driver/ws2812.c"
    "network/web_server.c"
    "network/wifi_ap.c"
    INCLUDE_DIRS "."
    REQUIRES
        driver
        esp_wifi
        esp_event
        nvs_flash
        esp_http_server
        spiffs
        json
        esp_timer
        app_update
        lwip
)
